### ISSUE TITLE
Duplicated actions are found

### ISSUE THREAD

**Issue by melroyvandenberg** [devops-actions/load-available-actions#319]
I notice that the same action is found multiple times, and creates duplicates

Is the search query maybe searching on all the branches? Meaning if there is let's say a `develop` and `main` branch, it will find the same action twice?

This is of course very confusing when people trying to lookup Actions in the marketplace. Maybe only stick to `main` or `master`? Or.. you need to detect duplicates some how using binary file comparison or checksums for instance. Or any other way to make the result unique (using org + repo + action name) as a unique ID.

**Comment by rajbos** [comment]
No it does not. The search API we use [here](https://github.com/devops-actions/load-available-actions/blob/1475d8d171e72373339d122fa2b07c86f553d6b7/src/main.ts#L153) only searches the default branch by default, see the [docs here](https://docs.github.com/en/rest/search?apiVersion=2022-11-28#search-code).

Closing this issue.
