### ISSUE TITLE
Add action path to the json output

### ISSUE THREAD

**Issue by jceresini** [devops-actions/load-available-actions#439]
In #250, support was added for actions in subdirectories. The json output includes the repo name, but it would be nice to include the path to the action as well. 

Example repo structure:
```
actions_repo/
├── some_action1
│   └── action.yml
└── some_action2
    └── action.yml
```

Example of new field:

```json
{
  ...
  
  "actions": [
    {
      "name": "some action 1",
      "repo": "actions_repo",
      "path": "some_action1"
    },
    {
      "name": "some action 2",
      "repo": "actions_repo",
      "path": "some_action2"
    },
  ]
  
  ...
  }

```

**Comment by rajbos** [comment]
Thanks for adding this! The new field is in the output and is empty for actions found in the root, or has a value when it is found in a subfolder:

![image](https://github.com/devops-actions/load-available-actions/assets/6085745/59742e88-f6b7-4b10-a327-85d22234deab)

Released in [v2.1.15](https://github.com/devops-actions/load-available-actions/releases/tag/v2.1.15).
